[package]
name = "floatconv-benchmark"
version = "0.1.0"
authors = ["Mara Bos <m-ou.se@m-ou.se>"]
edition = "2018"

[dependencies]
floatconv = { path = ".." }
criterion = "0.3"
compiler_builtins = "0.1.32"

[[bench]]
name = "benchmark"
path = "benchmark.rs"
harness = false
